### ISSUE TITLE
add Parallel and distributed testing

### ISSUE THREAD

**Issue by OlivieFranklova** [AbsaOSS/datasets-similarity#19]
Add pyrest-xdist

[Doc](https://github.com/absa-group/cps-handbook/blob/master/qa-strategy/testing/unit/Python-Unit-Tests-With-Pytest.md#pytest-xdist-parallel-and-distributed-testing)

```
stages:
  - test

test:
  stage: test
  script:
    - pip install pytest pytest-xdist
    - pytest -n auto --dist=loadscope
  ```
